config/routes.rb
Rails.application.routes.draw do
  root 'meetups#index'

  get '/signup', to: 'users#new', as: :signup
  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :logout
  get '/confirm_email/:token' => 'users#confirm_email', as: :confirm_email
  resources :comments, only: [:create]
  resources :meetups
  resources :users, only: [:new, :create]

  if Rails.env.development?
    get '/mail_previews(/:action(/:id(.:format)))' => 'mail_previews#:action'
  end

  namespace :api do
    get '/auth_token', to: 'users#auth_token', as: :auth_token
    resources :users
    resources :meetups
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates_presence_of :content
  belongs_to :user
  belongs_to :meetup, counter_cache: true
end

app/models/meetup.rb
class Meetup < ApplicationRecord
  validates_presence_of :title, :date, :address

  belongs_to :user
  has_many :comments, -> { order(:created_at => :asc) }, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_secure_token :auth_token
  has_secure_token :confirm_token
  validates :name, presence: true, uniqueness: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false },
            length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }

  before_save { self.email = email.downcase }

  has_many :meetups
  has_many :comments

  def email_confirmed?
    confirmed_at ? true : false
  end
end

app/controllers/api/api_controller.rb
module Api
  class ApiController < ActionController::API

    private
    def authorized_user
      @current_user = request.env['authorized_user']
    end
  end
end

app/controllers/api/meetups_controller.rb
module Api
  class MeetupsController < ApiController
    before_action :authorized_user

    def index
      @meetups = Meetup.includes(:user, :comments).order(created_at: :desc).all
    end
  end
end

app/controllers/api/users_controller.rb
module Api
  class UsersController < ApiController
    before_action :authorized_user

    def create

    end

    def auth_token
      @current_user.regenerate_auth_token
      render json: {auth_token: @current_user.auth_token}
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize_user
    unless current_user
      redirect_to(login_path, alert: '请先登录！') and return
    end

    unless current_user.email_confirmed?
      redirect_to(meetups_path, alert: '请先验证邮箱！')
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authorize_user, only: [:create]

  def create
    @comment = Comment.new(comment_params)

    current_user.comments << @comment
    if @comment.save
      redirect_to @comment.meetup, notice: '创建评论成功！'
    else
      @meetup = @comment.meetup
      @comments = @meetup.comments.includes(:user).all
      render 'meetups/show'
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:content, :meetup_id)
    end
end

app/controllers/mail_previews_controller.rb
class MailPreviewsController < ApplicationController
  def mail_confirm
    @user = User.find(params[:id])
    render file: 'user_mailer/mail_confirm', layout: 'mailer'
  end
end

app/controllers/meetups_controller.rb
class MeetupsController < ApplicationController
  before_action :set_meetup, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user, only: [:new, :create, :update, :edit, :destroy]

  def index
    @meetups = Meetup.includes(:user).order(created_at: :desc)
  end

  def new
    @meetup = Meetup.new
  end

  def show
    @comment = Comment.new(meetup: @meetup)
    @comments = @meetup.comments.includes(:user).order(created_at: :asc).all
  end

  def edit
  end

  def create
    @meetup = Meetup.new(meetup_params)

    current_user.meetups << @meetup
    if @meetup.save
      redirect_to @meetup, notice: '聚会创建成功！'
    else
      render :new
    end
  end

  def update
    if @meetup.update(meetup_params)
      redirect_to @meetup, notice: '聚会编辑成功！'
    else
      render :edit
    end
  end

  def destroy
    @meetup.destroy
    redirect_to meetups_url, notice: '聚会删除成功！'
  end

  private
    def set_meetup
      @meetup = Meetup.find(params[:id])
    end

    def meetup_params
      params[:meetup][:date] = params[:meetup][:date].in_time_zone("Beijing")
      params.require(:meetup).permit(:title, :date, :address, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to meetups_path, notice: '登录成功！'
    else
      flash.now[:error] = '邮箱或密码错误！'
      render 'new'
    end
  end

  def destroy
    session.clear
    redirect_to meetups_path, notice: '注销成功！'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      UserMailer.mail_confirm(@user).deliver_now
      session[:user_id] = @user.id
      redirect_to meetups_path, notice: '注册成功，已经向你的邮箱发送一封验证邮件！'
    else
      render :new
    end
  end

  def confirm_email
    user = User.find_by!(confirm_token: params[:token])
    user.update(confirmed_at: Time.now)
    session.clear
    redirect_to login_path, notice: '邮箱验证成功，请重新登录！'
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  BOOTSTRAP_FLASH_MSG = {
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
  }

  def bootstrap_class_for(flash_type)
    BOOTSTRAP_FLASH_MSG.fetch(flash_type.to_sym, flash_type.to_s)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/meetups_helper.rb
module MeetupsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Meet You</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Meet You", root_path, class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to '主页', meetups_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                  <span class="glyphicon glyphicon-star"></span> <%= current_user.name %> <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <%= link_to '<span class="glyphicon glyphicon-log-out"></span> 注销'.html_safe, logout_path, method: :delete, data: { confirm: '确认注销帐号吗？'} %>
                  </li>
                </ul>
              </li>
          <% else %>
            <li>
              <%= link_to '<span class="glyphicon glyphicon-user"></span> 注册'.html_safe, signup_path %>
            </li>
            <li>
              <%= link_to '<span class="glyphicon glyphicon-log-in"></span> 登录'.html_safe, login_path %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <div class="col-md-8 col-md-offset-2">
      <% if current_user && !current_user.email_confirmed? %>
        <div class="alert alert-warning">你还没有验证邮箱！<%= link_to('验证(仅开发环境可用)', "/mail_previews/mail_confirm/#{current_user.id}") if Rails.env.development? %></div>
      <% end %>

      <% flash.each do |name, msg| %>
        <%= content_tag :div, class: "alert #{bootstrap_class_for(name)} alert-dismissable", role: "alert" do %>
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <%= msg %>
        <% end %>
      <% end %>

      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/meetups/_form.html.erb
<%= form_for(meetup, html: { class: "form-horizontal", role: "form" }) do |f| %>
    <% if meetup.errors.any? %>
        <div class="alert alert-danger alert-dismissable" role="alert">
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4>你提交的数据有<%= meetup.errors.count %>个问题：</h4>

          <ul>
            <% meetup.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

  <div class="form-group">
    <%= f.label :title, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :date, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :date, value: meetup.date.try(:strftime, '%Y-%m-%d %H:%M'), class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :address, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :address, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :content, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :content, rows: 10, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit '提交', class: "btn btn-primary" %>
      <%= link_to '返回', meetups_path, class: "btn btn-info" %>
    </div>
  </div>
<% end %>

app/views/meetups/edit.html.erb
<h1>聚会编辑</h1>

<%= render 'form', meetup: @meetup %>

app/views/meetups/index.html.erb
<ul class="meetup-list">
  <% @meetups.each do |meetup| %>
    <li>
      <span class="meetup-title"><%= link_to meetup.title, meetup_path(meetup) %></span>
      <span class="meetup-info">
        由 <%= meetup.user.name %> 创建于 <%= meetup.created_at.strftime('%Y年%m月%d日 %H:%M') %> |
        <%= meetup.comments_count %> 条评论
      </span>
    </li>
  <% end %>
</ul>

<div class="new-meetup">
  <%= link_to '发起聚会', new_meetup_path, class: 'btn btn-success' %>
</div>

app/views/meetups/new.html.erb
<h1>创建聚会</h1>

<%= render 'form', meetup: @meetup %>

app/views/meetups/show.html.erb
<h2>
  <%= @meetup.title %>
  <% if current_user && @meetup.user.id == current_user.id %>
    <small><%= link_to '编辑', edit_meetup_path(@meetup) %> | <%= link_to '删除', @meetup, method: :delete, data: {confirm: '确定删除吗？'} %></small>
  <% end %>
</h2>

<div class="meetup-detail">
  <p>
    <strong>发起人</strong><br>
    <%= @meetup.user.name %>
  </p>

  <p>
    <strong>时间</strong><br>
    <%= @meetup.date.strftime('%Y年%m月%d日 %H:%M') %>
  </p>

  <p>
    <strong>地点</strong><br>
    <%= @meetup.address %>
  </p>

  <p>
    <strong>内容</strong><br>
    <%= simple_format @meetup.content %>
  </p>
</div>

<div class="meetup-comments">
  <% @comments.each do |comment| %>
    <div class="comment">
      <strong><%= comment.user.name %> <small>发表于 <%= comment.created_at.strftime('%Y年%m月%d日 %H:%M') %></small></strong>
      <%=simple_format comment.content %>
    </div>
  <% end %>
</div>

<% if current_user %>
    <%= form_for(@comment, html: {class: "form-horizontal", role: "form"}) do |f| %>
        <%= f.hidden_field :meetup_id %>

        <div class="form-group">
          <div class="col-md-12">
            <%= f.text_area :content, class: "form-control" %>
            <%= f.submit '发表评论', class: "btn btn-primary new-comment-btn" %>
          </div>
        </div>

        <% if @comment.errors.any? %>
            <ul>
              <% @comment.errors.full_messages.each do |message| %>
                  <li class="text-danger"><%= message %></li>
              <% end %>
            </ul>
        <% end %>
    <% end %>
<% else %>
    <p>请登录后发表评论！</p>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4>你提交的数据有<%= @user.errors.count %>个问题：</h4>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.password_field :password, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit '提交', class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="page-header">
  <h1>注册</h1>
</div>

<%= render 'form' %>